models.py
from datetime import datetime

from app import db


def slugify(str_to_slugify):
    str_to_slugify_list = str_to_slugify.lower().split()
    map_lambda = lambda str: str.replace('-', '')
    filter_lambda = lambda str: bool(str)
    return '-'.join(filter(filter_lambda, map(map_lambda, str_to_slugify_list)))


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(140), nullable=False)
    slug = db.Column(db.String(140), unique=True)
    created_on = db.Column(db.DateTime(), default=datetime.utcnow)
    updated_on = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return "Post <id:{}, title:{}>".format(self.id, self.title)

app/__init__.py
from flask import Flask
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy

from config import Config

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

from app import view

articles/blueprint.py
from flask import Blueprint
from flask import render_template

articles = Blueprint('articles', __name__, template_folder='templates')


@articles.route('/')
def index():
    return render_template('articles/index.html', n="Oleg")

main.py
from app import app
from posts.blueprint import posts
from articles.blueprint import articles

app.register_blueprint(posts, url_prefix='/blog')
app.register_blueprint(articles, url_prefix='/articles')

if __name__ == '__main__':
    print("app.run()", __name__)
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post

from articles.blueprint import index as articles_index

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/')
def index():
    posts = Post.query.order_by(Post.id).all()
    return render_template('posts/index.html', posts=posts)


@posts.route('/articles')
def articles():
    return articles_index()

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}
            {% endblock %} | Blog
        </title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('index') }}">Автоальянс</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('articles.index') }}">
                            Асортимент<span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.index') }}">
                            Новости <span class="sr-only">(current)</span>
                        </a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <a class="nav-link" href="">
                        Корзина <span class="badge badge-success">4</span>
                    </a>
                </form>
            </div>
        </nav>

        <div class="container">
                {% block contant %}
                {% endblock %}
        </div>

    </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Root Index
{% endblock %}

{% block contant %}
    Hello Root Index Page
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}
    Posts Index
{% endblock %}

{% block contant %}
    Articles Index Page
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Posts Index
{% endblock %}

{% block contant %}
    Posts Index Page

    {% for post in posts %}
        <div>{{ post }}</div>
    {% endfor %}
{% endblock %}